from rest_framework import serializers

from api.models import Patient


class PatientSerializer(serializers.HyperlinkedModelSerializer):
    
    """
    Converts Patient model instances into JSON and validates incoming patient data.

    Only the selected fields are exposed through the API. The patient_id field is
    generated by the database and is mainly used as the unique identifier.
    """

    class Meta:
        model = Patient
        fields = (
            "patient_id",
            "first_name",
            "last_name",
            "blood",
        )
        read_only_fields = ("patient_id",)